#!/bin/sh

# License: 
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more detai

for yaml_file in `find . -name \*.yml`; do
    ansible-playbook --syntax-check ${yaml_file} > /dev/null 2>&1
    if [ $? -gt 0 ]; then
        echo "ERROR: Found a syntax error with ${yaml_file}"
        echo "ERROR: Please run ansible-playbook --syntax-check ${yaml_file} to view the error"
        exit 1
    fi
done
