#!/bin/sh
#
# Program: Netbackup status <nbstatus>
#
# Author: Matty < matty91 at gmail dot com >
#
# Current Version: 1.0
#
# License:
#  Copyright (C) 2007 Matty <matty91 at gmail dot com>
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.

ADMIN="ops@prefetch.net"
HOURS=24
TEMP="/var/tmp/nbstatus.txt"

/opt/openv/netbackup/bin/admincmd/bpdbjobs -summary -L -keep_hours ${HOURS} > ${TEMP}
/opt/openv/netbackup/bin/admincmd/bperror -U -problems -hoursago ${HOURS} >> ${TEMP}

mailx -s "Netbackup status last $HOURS hours" ${ADMIN} < ${TEMP}
rm ${TEMP}
