#!/bin/bash
#
# Program: NFS throughput statistics <nfsrwstat.sh>
#
# Author: Matty < matty91 at gmail dot com >
#
# Current Version: 1.0
#
# Revision History:
#
#  Version 1.0
#    Initial Release
#
# Last Updated: 10-28-2011
#
# Purpose:
#  nfsrwstat.sh will display the number of bytes read and written
# by the in-kernel nfsd threads.
#
# License:
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.

PROC_NFSD="/proc/net/rpc/nfsd"
SLEEP_INTERVAL=5

byteswritten=0
bytesread=0
totalwritten=0
totalread=0

printf "%-10s %-10s %-10s\n" Date "Bytes_Read" "Bytes_Written"

while :
do
    input=$(grep io ${PROC_NFSD})
    set -- $input
    bytesread=$2
    byteswritten=$3

    totalwritten=$((${byteswritten} - $totalwritten))
    totalread=$((${bytesread} - ${totalread}))

    printf "%-10s %-10d %-10d\n" `date "+%H:%M:%S"` $totalread $totalwritten

    totalwritten=${byteswritten}
    totalread=${bytesread}    
    sleep ${SLEEP_INTERVAL}
done
