#!/bin/sh
#
# Program: rescan-mapper-device
#
# Author: Matty < matty91 at gmail dot com >
#
# Current Version: 1.0
#
# Revision History:
#
# Version 1.0
#     Original release
#
# Last Updated: 04-07-2017
#
# Purpose:
#   Sample script to rescan the sd devices in a mapper device to 
#   pick up changes (LUN size increase for example).
#
# License:
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License as published by the
#   Free Software Foundation; either version 2, or (at your option) any
#   later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#

DEVS="MAPPER_DEVICE"

for dev in ${DEVS}; do
   multipath -ll ${dev} | awk '/sd/ {print $3}' | while read bd; do
       if [ -b /dev/${bd} ]; then
           echo "Processing ${dev} / ${bd}"
           echo "  Current size: `cat /sys/block/${bd}/size`"
           echo 1 > /sys/block/${bd}/device/rescan
           echo "  New size: `cat /sys/block/${bd}/size`"
       fi
   done
done
